import type { ReactNode } from 'react'
import { useKeycloak } from './KeycloakProvider'

export const PERMISSIONS = {
  LIS_WORKLIST_VIEW: 'LIS_WORKLIST_VIEW',
  LIS_ORDER_CREATE: 'LIS_ORDER_CREATE',
  LIS_SPECIMEN_COLLECT: 'LIS_SPECIMEN_COLLECT',
  LIS_SPECIMEN_RECEIVE: 'LIS_SPECIMEN_RECEIVE',
  LIS_RESULT_ENTER: 'LIS_RESULT_ENTER',
  LIS_RESULT_VALIDATE: 'LIS_RESULT_VALIDATE',
  LIS_CRITICAL_NOTIFY: 'LIS_CRITICAL_NOTIFY',
  BLOOD_BANK_VIEW: 'BLOOD_BANK_VIEW',
  BLOOD_UNIT_RECEIVE: 'BLOOD_UNIT_RECEIVE',
  TRANSFUSION_REQUEST: 'TRANSFUSION_REQUEST',
  TRANSFUSION_CROSSMATCH: 'TRANSFUSION_CROSSMATCH',
  TRANSFUSION_ISSUE: 'TRANSFUSION_ISSUE',
  TRANSFUSION_COMPLETE: 'TRANSFUSION_COMPLETE',
  TRANSFUSION_REACTION_REPORT: 'TRANSFUSION_REACTION_REPORT',
  RIS_WORKLIST_VIEW: 'RIS_WORKLIST_VIEW',
  RIS_STUDY_CREATE: 'RIS_STUDY_CREATE',
  RIS_STUDY_SCHEDULE: 'RIS_STUDY_SCHEDULE',
  RIS_STUDY_CHECK_IN: 'RIS_STUDY_CHECK_IN',
  RIS_STUDY_PERFORM: 'RIS_STUDY_PERFORM',
  RIS_STUDY_REPORT: 'RIS_STUDY_REPORT',
  PHARMACY_VIEW: 'PHARMACY_VIEW',
  PHARMACY_PRODUCT_CREATE: 'PHARMACY_PRODUCT_CREATE',
  PHARMACY_LOT_RECEIVE: 'PHARMACY_LOT_RECEIVE',
  PHARMACY_DISPENSATION_VALIDATE: 'PHARMACY_DISPENSATION_VALIDATE',
  PHARMACY_DISPENSE: 'PHARMACY_DISPENSE',
  DPI_ENCOUNTER_CREATE: 'DPI_ENCOUNTER_CREATE',
  DPI_VITAL_RECORD: 'DPI_VITAL_RECORD',
  DPI_MEDICATION_PRESCRIBE: 'DPI_MEDICATION_PRESCRIBE',
  DPI_LAB_ORDER_CREATE: 'DPI_LAB_ORDER_CREATE',
  DPI_LAB_RESULT_ENTER: 'DPI_LAB_RESULT_ENTER',
  RCM_VIEW: 'RCM_VIEW',
  RCM_INVOICE_CREATE: 'RCM_INVOICE_CREATE',
  RCM_INVOICE_ISSUE: 'RCM_INVOICE_ISSUE',
  RCM_PAYMENT_RECORD: 'RCM_PAYMENT_RECORD',
  RCM_CLAIM_CREATE: 'RCM_CLAIM_CREATE',
  RCM_CLAIM_SUBMIT: 'RCM_CLAIM_SUBMIT',
  RCM_CLAIM_ADJUDICATE: 'RCM_CLAIM_ADJUDICATE',
  HR_VIEW: 'HR_VIEW',
  HR_STAFF_CREATE: 'HR_STAFF_CREATE',
  HR_CREDENTIAL_CREATE: 'HR_CREDENTIAL_CREATE',
  HR_CREDENTIAL_RENEW: 'HR_CREDENTIAL_RENEW',
  HR_SHIFT_CREATE: 'HR_SHIFT_CREATE',
  HR_SHIFT_PUBLISH: 'HR_SHIFT_PUBLISH',
  HR_SHIFT_CANCEL: 'HR_SHIFT_CANCEL',
} as const

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]

const rolePermissions: Record<Permission, readonly string[]> = {
  LIS_WORKLIST_VIEW: ['MEDECIN', 'INFIRMIER', 'BIOLOGISTE', 'SUPER_ADMIN'],
  LIS_ORDER_CREATE: ['MEDECIN', 'SUPER_ADMIN'],
  LIS_SPECIMEN_COLLECT: ['INFIRMIER', 'BIOLOGISTE', 'SUPER_ADMIN'],
  LIS_SPECIMEN_RECEIVE: ['BIOLOGISTE', 'SUPER_ADMIN'],
  LIS_RESULT_ENTER: ['BIOLOGISTE', 'SUPER_ADMIN'],
  LIS_RESULT_VALIDATE: ['BIOLOGISTE', 'SUPER_ADMIN'],
  LIS_CRITICAL_NOTIFY: ['BIOLOGISTE', 'SUPER_ADMIN'],
  BLOOD_BANK_VIEW: ['MEDECIN', 'INFIRMIER', 'BIOLOGISTE', 'SUPER_ADMIN'],
  BLOOD_UNIT_RECEIVE: ['INFIRMIER', 'BIOLOGISTE', 'SUPER_ADMIN'],
  TRANSFUSION_REQUEST: ['MEDECIN', 'SUPER_ADMIN'],
  TRANSFUSION_CROSSMATCH: ['BIOLOGISTE', 'SUPER_ADMIN'],
  TRANSFUSION_ISSUE: ['BIOLOGISTE', 'SUPER_ADMIN'],
  TRANSFUSION_COMPLETE: ['INFIRMIER', 'BIOLOGISTE', 'SUPER_ADMIN'],
  TRANSFUSION_REACTION_REPORT: ['INFIRMIER', 'BIOLOGISTE', 'SUPER_ADMIN'],
  RIS_WORKLIST_VIEW: ['MEDECIN', 'INFIRMIER', 'RADIOLOGUE', 'MANIPULATEUR', 'SUPER_ADMIN'],
  RIS_STUDY_CREATE: ['MEDECIN', 'SUPER_ADMIN'],
  RIS_STUDY_SCHEDULE: ['MANIPULATEUR', 'RADIOLOGUE', 'SUPER_ADMIN'],
  RIS_STUDY_CHECK_IN: ['MANIPULATEUR', 'RADIOLOGUE', 'SUPER_ADMIN'],
  RIS_STUDY_PERFORM: ['MANIPULATEUR', 'RADIOLOGUE', 'SUPER_ADMIN'],
  RIS_STUDY_REPORT: ['RADIOLOGUE', 'SUPER_ADMIN'],
  PHARMACY_VIEW: ['MEDECIN', 'INFIRMIER', 'PHARMACIEN', 'SUPER_ADMIN'],
  PHARMACY_PRODUCT_CREATE: ['PHARMACIEN', 'SUPER_ADMIN'],
  PHARMACY_LOT_RECEIVE: ['PHARMACIEN', 'SUPER_ADMIN'],
  PHARMACY_DISPENSATION_VALIDATE: ['PHARMACIEN', 'SUPER_ADMIN'],
  PHARMACY_DISPENSE: ['PHARMACIEN', 'SUPER_ADMIN'],
  DPI_ENCOUNTER_CREATE: ['MEDECIN', 'SUPER_ADMIN'],
  DPI_VITAL_RECORD: ['INFIRMIER', 'MEDECIN', 'SUPER_ADMIN'],
  DPI_MEDICATION_PRESCRIBE: ['MEDECIN', 'SUPER_ADMIN'],
  DPI_LAB_ORDER_CREATE: ['MEDECIN', 'SUPER_ADMIN'],
  DPI_LAB_RESULT_ENTER: ['BIOLOGISTE', 'SUPER_ADMIN'],
  RCM_VIEW: ['COMPTABLE', 'CAISSIER', 'FACTURATION', 'RESPONSABLE_FINANCIER', 'SUPER_ADMIN'],
  RCM_INVOICE_CREATE: ['FACTURATION', 'RESPONSABLE_FINANCIER', 'SUPER_ADMIN'],
  RCM_INVOICE_ISSUE: ['CAISSIER', 'RESPONSABLE_FINANCIER', 'SUPER_ADMIN'],
  RCM_PAYMENT_RECORD: ['CAISSIER', 'RESPONSABLE_FINANCIER', 'SUPER_ADMIN'],
  RCM_CLAIM_CREATE: ['FACTURATION', 'RESPONSABLE_FINANCIER', 'SUPER_ADMIN'],
  RCM_CLAIM_SUBMIT: ['FACTURATION', 'RESPONSABLE_FINANCIER', 'SUPER_ADMIN'],
  RCM_CLAIM_ADJUDICATE: ['FACTURATION', 'RESPONSABLE_FINANCIER', 'SUPER_ADMIN'],
  HR_VIEW: ['RH_MANAGER', 'PLANNING_RH', 'SUPER_ADMIN'],
  HR_STAFF_CREATE: ['RH_MANAGER', 'SUPER_ADMIN'],
  HR_CREDENTIAL_CREATE: ['RH_MANAGER', 'SUPER_ADMIN'],
  HR_CREDENTIAL_RENEW: ['RH_MANAGER', 'SUPER_ADMIN'],
  HR_SHIFT_CREATE: ['RH_MANAGER', 'PLANNING_RH', 'SUPER_ADMIN'],
  HR_SHIFT_PUBLISH: ['RH_MANAGER', 'PLANNING_RH', 'SUPER_ADMIN'],
  HR_SHIFT_CANCEL: ['RH_MANAGER', 'PLANNING_RH', 'SUPER_ADMIN'],
}

export function usePermissions() {
  const { hasRole, isLoading } = useKeycloak()

  const can = (permission: Permission) => rolePermissions[permission].some((role) => hasRole(role))
  const canAny = (...permissions: Permission[]) => permissions.some(can)
  const canAll = (...permissions: Permission[]) => permissions.every(can)

  return { can, canAny, canAll, isLoading }
}

interface CanProps {
  permission: Permission
  children: ReactNode
  fallback?: ReactNode
}

export function Can({ permission, children, fallback = null }: CanProps) {
  const { can, isLoading } = usePermissions()
  if (isLoading || !can(permission)) return <>{fallback}</>
  return <>{children}</>
}
