import { useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { AlertTriangle, Beaker, CheckCircle2, ClipboardPlus, Search, TestTube2 } from 'lucide-react'
import { Badge, Button, Card, CardBody, EmptyState, Input, Modal, Select, Spinner, StatCard, Table, Td, Th, Thead, Tr } from '@/components/ui'
import { lisService } from '@/services/lis.service'
import type { LaboratoryInterpretation, LaboratoryOrder, LaboratoryStatus } from '@/types'

const STATUS_LABELS: Record<LaboratoryStatus, string> = {
  ORDERED: 'Prescrit', COLLECTED: 'Prélevé', RECEIVED: 'Reçu', IN_ANALYSIS: 'En analyse', TECHNICALLY_VALIDATED: 'Validé techniquement', BIOLOGICALLY_VALIDATED: 'Validé biologiquement', CANCELLED: 'Annulé',
}
const statusVariant = (status: LaboratoryStatus) => status === 'BIOLOGICALLY_VALIDATED' ? 'normal' : status === 'CANCELLED' ? 'danger' : status === 'ORDERED' ? 'info' : 'warning' as const

export default function LaboratoryWorklistPage() {
  const queryClient = useQueryClient()
  const [search, setSearch] = useState('')
  const [status, setStatus] = useState<LaboratoryStatus | ''>('')
  const [createOpen, setCreateOpen] = useState(false)
  const [resultOrder, setResultOrder] = useState<LaboratoryOrder | null>(null)
  const { data: orders = [], isLoading } = useQuery({ queryKey: ['lis-orders'], queryFn: () => lisService.list() })
  const refresh = () => queryClient.invalidateQueries({ queryKey: ['lis-orders'] })
  const action = useMutation({ mutationFn: ({ id, operation }: { id: number; operation: 'collect' | 'receive' | 'validate' | 'notify' }) => operation === 'collect' ? lisService.collect(id, 'Utilisateur laboratoire') : operation === 'receive' ? lisService.receive(id, 'Utilisateur laboratoire') : operation === 'validate' ? lisService.validate(id, 'Biologiste') : lisService.notifyCritical(id, 'Médecin prescripteur'), onSuccess: refresh })
  const filtered = useMemo(() => orders.filter((order) => (!status || order.status === status) && `${order.patientRef} ${order.examName} ${order.barcode}`.toLowerCase().includes(search.toLowerCase())), [orders, search, status])
  const critical = orders.filter((order) => order.results.some((result) => result.interpretation.startsWith('CRITICAL'))).length
  return <div className="space-y-6">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-bold text-text-primary">Laboratoire — LIS</h1><p className="mt-1 text-sm text-text-muted">Traçabilité pré-analytique, résultats et validation biologique.</p></div><Button icon={<ClipboardPlus className="h-4 w-4" />} onClick={() => setCreateOpen(true)}>Nouvelle demande</Button></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="File active" value={orders.filter((item) => !['BIOLOGICALLY_VALIDATED', 'CANCELLED'].includes(item.status)).length} icon={<TestTube2 className="h-5 w-5" />} /><StatCard label="À prélever" value={orders.filter((item) => item.status === 'ORDERED').length} icon={<Beaker className="h-5 w-5" />} color="warning" /><StatCard label="Résultats critiques" value={critical} icon={<AlertTriangle className="h-5 w-5" />} color="danger" /><StatCard label="Validés" value={orders.filter((item) => item.status === 'BIOLOGICALLY_VALIDATED').length} icon={<CheckCircle2 className="h-5 w-5" />} color="success" /></div>
    <Card><CardBody className="space-y-4"><div className="flex flex-col gap-3 md:flex-row"><Input aria-label="Rechercher un ordre" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Patient, examen ou code-barres" icon={<Search className="h-4 w-4" />} /><Select aria-label="Filtrer par statut" value={status} onChange={(event) => setStatus(event.target.value as LaboratoryStatus | '')} options={[{ value: '', label: 'Tous les statuts' }, ...Object.entries(STATUS_LABELS).map(([value, label]) => ({ value, label }))]} /></div>{isLoading ? <div className="flex justify-center py-12"><Spinner /></div> : filtered.length === 0 ? <EmptyState icon={<TestTube2 className="h-8 w-8" />} title="Aucun ordre de laboratoire" description="Les demandes issues du DPI apparaîtront ici." /> : <Table><Thead><tr><Th>Patient / code-barres</Th><Th>Examen</Th><Th>Priorité</Th><Th>Statut</Th><Th>Résultats</Th><Th className="text-right">Actions</Th></tr></Thead><tbody>{filtered.map((order) => { const hasCritical = order.results.some((result) => result.interpretation.startsWith('CRITICAL')); return <Tr key={order.id}><Td><p className="font-medium">{order.patientRef}</p><p className="font-mono text-xs text-text-muted">{order.barcode}</p></Td><Td><p>{order.examName}</p><p className="text-xs text-text-muted">{order.sampleType}</p></Td><Td><Badge variant={order.priority === 'STAT' ? 'danger' : order.priority === 'URGENT' ? 'warning' : 'neutral'}>{order.priority}</Badge></Td><Td><Badge variant={statusVariant(order.status)}>{STATUS_LABELS[order.status]}</Badge></Td><Td>{order.results.length > 0 ? <div className="flex items-center gap-1"><span>{order.results.length}</span>{hasCritical && <AlertTriangle className="h-4 w-4 text-clinical-danger" aria-label="Valeur critique" />}</div> : '—'}</Td><Td><div className="flex justify-end gap-2">{order.status === 'ORDERED' && <Button size="sm" variant="outline" loading={action.isPending} onClick={() => action.mutate({ id: order.id, operation: 'collect' })}>Prélever</Button>}{order.status === 'COLLECTED' && <Button size="sm" variant="outline" loading={action.isPending} onClick={() => action.mutate({ id: order.id, operation: 'receive' })}>Réceptionner</Button>}{['RECEIVED', 'IN_ANALYSIS'].includes(order.status) && <Button size="sm" onClick={() => setResultOrder(order)}>Saisir résultat</Button>}{order.status === 'IN_ANALYSIS' && <Button size="sm" variant="outline" loading={action.isPending} onClick={() => action.mutate({ id: order.id, operation: 'validate' })}>Valider</Button>}{hasCritical && !order.criticalNotifiedAt && <Button size="sm" variant="danger" loading={action.isPending} onClick={() => action.mutate({ id: order.id, operation: 'notify' })}>Alerter</Button>}</div></Td></Tr>})}</tbody></Table>}</CardBody></Card>
    <CreateOrderModal open={createOpen} onClose={() => setCreateOpen(false)} onSuccess={refresh} />
    <ResultModal order={resultOrder} onClose={() => setResultOrder(null)} onSuccess={refresh} />
  </div>
}

function CreateOrderModal({ open, onClose, onSuccess }: { open: boolean; onClose: () => void; onSuccess: () => void }) {
  const [form, setForm] = useState({ clinicalEncounterId: '', patientRef: '', examName: '', examCode: '', sampleType: 'SANG', priority: 'ROUTINE' })
  const mutation = useMutation({ mutationFn: () => lisService.create({ clinicalEncounterId: Number(form.clinicalEncounterId), patientRef: form.patientRef, examName: form.examName, examCode: form.examCode || undefined, sampleType: form.sampleType, priority: form.priority as LaboratoryOrder['priority'], orderedBy: 'Médecin prescripteur' }), onSuccess: () => { onSuccess(); onClose() } })
  return <Modal open={open} onClose={onClose} title="Créer une demande de laboratoire"><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); mutation.mutate() }}><div className="grid gap-4 sm:grid-cols-2"><Input label="ID dossier clinique" type="number" required value={form.clinicalEncounterId} onChange={(event) => setForm({ ...form, clinicalEncounterId: event.target.value })} /><Input label="Référence patient" required value={form.patientRef} onChange={(event) => setForm({ ...form, patientRef: event.target.value })} /><Input label="Examen" required value={form.examName} onChange={(event) => setForm({ ...form, examName: event.target.value })} /><Input label="Code LOINC (optionnel)" value={form.examCode} onChange={(event) => setForm({ ...form, examCode: event.target.value })} /><Select label="Type d’échantillon" value={form.sampleType} onChange={(event) => setForm({ ...form, sampleType: event.target.value })} options={[{ value: 'SANG', label: 'Sang' }, { value: 'URINE', label: 'Urine' }, { value: 'SELLES', label: 'Selles' }, { value: 'AUTRE', label: 'Autre' }]} /><Select label="Priorité" value={form.priority} onChange={(event) => setForm({ ...form, priority: event.target.value })} options={[{ value: 'ROUTINE', label: 'Routine' }, { value: 'URGENT', label: 'Urgent' }, { value: 'STAT', label: 'Immédiat (STAT)' }]} /></div>{mutation.isError && <p className="text-sm text-clinical-danger">La demande n’a pas pu être créée. Vérifiez les informations saisies.</p>}<div className="flex justify-end gap-3"><Button type="button" variant="ghost" onClick={onClose}>Annuler</Button><Button type="submit" loading={mutation.isPending}>Créer</Button></div></form></Modal>
}

function ResultModal({ order, onClose, onSuccess }: { order: LaboratoryOrder | null; onClose: () => void; onSuccess: () => void }) {
  const [form, setForm] = useState({ analyteName: '', resultValue: '', unit: '', referenceRange: '', interpretation: 'NORMAL' as LaboratoryInterpretation })
  const mutation = useMutation({ mutationFn: () => lisService.addResult(order!.id, { ...form, technicalValidator: 'Technicien laboratoire' }), onSuccess: () => { onSuccess(); onClose() } })
  return <Modal open={Boolean(order)} onClose={onClose} title={`Résultat — ${order?.examName ?? ''}`}><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); mutation.mutate() }}><div className="grid gap-4 sm:grid-cols-2"><Input label="Analyte" required value={form.analyteName} onChange={(event) => setForm({ ...form, analyteName: event.target.value })} /><Input label="Résultat" required value={form.resultValue} onChange={(event) => setForm({ ...form, resultValue: event.target.value })} /><Input label="Unité" value={form.unit} onChange={(event) => setForm({ ...form, unit: event.target.value })} /><Input label="Intervalle de référence" value={form.referenceRange} onChange={(event) => setForm({ ...form, referenceRange: event.target.value })} /><Select label="Interprétation" value={form.interpretation} onChange={(event) => setForm({ ...form, interpretation: event.target.value as LaboratoryInterpretation })} options={['NORMAL', 'LOW', 'HIGH', 'ABNORMAL', 'CRITICAL_LOW', 'CRITICAL_HIGH'].map((value) => ({ value, label: value.replace(/_/g, ' ') }))} /></div><div className="flex justify-end gap-3"><Button type="button" variant="ghost" onClick={onClose}>Annuler</Button><Button type="submit" loading={mutation.isPending}>Enregistrer</Button></div></form></Modal>
}
