# ============================================================================
# Profil SECURE — Tenant Service avec Keycloak OAuth2/JWT
# ============================================================================
spring:
  datasource:
    url: jdbc:h2:mem:tenantdb_secure;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: false

  # OAuth2 Resource Server — Keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/ehealth}
          jwk-set-uri: ${KEYCLOAK_JWK_URI:http://localhost:8180/realms/ehealth/protocol/openid-connect/certs}

server:
  port: 8084

logging:
  level:
    com.sih.tenant: DEBUG
    org.springframework.security: INFO
    org.springframework.security.oauth2: DEBUG
